deploy:
	# nix run nixpkgs#nixos-rebuild switch -- --flake .#fieldops --target-host ec2-44-202-147-84.compute-1.amazonaws.com --build-host localhost --use-remote-sudo
	nix run nixpkgs#nixos-rebuild switch -- --flake .#fieldops --target-host nixos-bp --build-host localhost --use-remote-sudo
