#cloud-config

# Add groups to the system
groups:
  - users

users:
  - default
  %{~ for user in users ~}
  - name: ${user.username}
    gecos: ${user.fullname}
    groups: users
    sudo: ALL=(ALL) NOPASSWD:ALL
    lock_passwd: true
    ssh_authorized_keys:
    %{~ for pubkey in user.pubkeys ~}
      - ${pubkey}
    %{~ endfor ~}
  %{~ endfor ~}
